-- Migration 014: Commit-safe changes feed (ARCH-6)
-- seq is backfilled in (created_at, id) order and xid8 records the writing transaction; the
-- feed pages on (xid8, seq). Event-less owned surveys get one synthetic 'backfilled' event (D-03).
-- Both columns come from defaults, so event INSERT statements do not name them.
ALTER TABLE survey_events ADD COLUMN IF NOT EXISTS seq BIGINT;

UPDATE survey_events e SET seq = o.rn
  FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM survey_events) o
  WHERE o.id = e.id;

ALTER TABLE survey_events ALTER COLUMN seq SET NOT NULL;
ALTER TABLE survey_events ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('survey_events', 'seq'),
              COALESCE((SELECT MAX(seq) FROM survey_events), 0) + 1, false);

ALTER TABLE survey_events ADD COLUMN IF NOT EXISTS xid8 xid8 NOT NULL DEFAULT pg_current_xact_id();

CREATE UNIQUE INDEX IF NOT EXISTS idx_survey_events_xid8_seq ON survey_events (xid8, seq);

-- D-03: runs after setval so synthetic events take new seq values and the migration's xid8.
INSERT INTO survey_events (id, survey_id, actor_id, event_type, payload)
SELECT gen_random_uuid()::text, s.id, NULL, 'backfilled', jsonb_build_object('reason', 'migration_014')
FROM surveys s
WHERE s.user_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM survey_events e WHERE e.survey_id = s.id);
