import { StyleSheet } from "react-native"
import {
  brandColors,
  brandRadius,
  brandShadow,
  brandSpacing,
  brandTypography,
} from "../app/brand-tokens"

export const styles = StyleSheet.create({
  mainScroll: {
    flex: 1,
    backgroundColor: brandColors.canvas,
  },
  detailScreenContent: {
    padding: brandSpacing.md,
    gap: brandSpacing.md,
    paddingBottom: 120,
  },
  detailHeroStickyWrap: {
    backgroundColor: brandColors.canvas,
  },
  detailHeroCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 34,
    backgroundColor: brandColors.forest,
    padding: 20,
    gap: 12,
    ...brandShadow.card,
  },
  detailHeroCardCompressed: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
  },
  detailHeroAccentOrb: {
    position: "absolute",
    top: -24,
    right: -18,
    width: 138,
    height: 138,
    borderRadius: 999,
    backgroundColor: "rgba(176, 199, 142, 0.22)",
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  detailHeroCopy: {
    flex: 1,
    gap: 8,
  },
  detailHeroEyebrow: {
    ...brandTypography.heroEyebrow,
    color: "#D7E3C0",
  },
  detailSurveyTitle: {
    ...brandTypography.heroTitle,
    color: brandColors.white,
  },
  detailHeroMetricCard: {
    minWidth: 116,
    maxWidth: 144,
    borderRadius: 24,
    backgroundColor: "rgba(247, 246, 240, 0.12)",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  detailHeroMetricLabel: {
    ...brandTypography.heroEyebrow,
    color: "#D7E3C0",
  },
  detailHeroMetricValue: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: "900",
    color: brandColors.white,
  },
  detailHeroMetricMeta: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  detailHeroCompactHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeroCompactCopy: {
    flex: 1,
    gap: 4,
  },
  detailHeroCompactTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 24,
    lineHeight: 27,
    color: brandColors.white,
  },
  detailHeroCompactMeta: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  detailHeroCompactMetricPill: {
    minWidth: 92,
    borderRadius: brandRadius.card,
    backgroundColor: "rgba(247, 246, 240, 0.12)",
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "flex-end",
    gap: 2,
  },
  detailHeroCompactMetricLabel: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  detailHeroCompactMetricValue: {
    ...brandTypography.label,
    fontSize: 18,
    lineHeight: 21,
    color: brandColors.white,
  },
  detailRenameRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },
  detailRenameField: {
    flex: 1,
    minWidth: 200,
  },
  detailRenameLabel: {
    color: "#D7E3C0",
  },
  detailRenameInput: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "rgba(255,255,255,0.12)",
    color: brandColors.white,
  },
  detailRenameSaveButton: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.sage,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailRenameSaveButtonText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  detailRenameCancelButton: {
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailRenameCancelButtonText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  detailHeroStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  },
  detailHeroStatusPill: {
    borderRadius: brandRadius.pill,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderWidth: 1,
  },
  detailHeroStatusPillNeutral: {
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(247, 246, 240, 0.1)",
  },
  detailHeroStatusPillSuccess: {
    borderColor: "rgba(187,208,155,0.28)",
    backgroundColor: "rgba(176,199,142,0.18)",
  },
  detailHeroStatusPillDanger: {
    borderColor: "rgba(228,165,149,0.28)",
    backgroundColor: "rgba(205,88,51,0.14)",
  },
  detailHeroStatusPillText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  heroMetaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroMetaText: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  detailHeroProgressCard: {
    gap: 8,
    borderRadius: 22,
    backgroundColor: "rgba(247, 246, 240, 0.1)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  detailHeroProgressCardCompact: {
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  detailHeroProgressHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeroProgressLabel: {
    ...brandTypography.heroEyebrow,
    color: "#D7E3C0",
  },
  detailHeroProgressValue: {
    ...brandTypography.label,
    color: brandColors.white,
  },
  detailHeroProgressTrack: {
    height: 10,
    overflow: "hidden",
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(255,255,255,0.14)",
  },
  detailHeroProgressFill: {
    height: "100%",
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.sage,
  },
  detailHeroProgressFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  detailHeroSubmitCard: {
    gap: 10,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(247, 246, 240, 0.08)",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  detailHeroSubmitCardCompact: {
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  detailHeroSubmitCardReady: {
    borderColor: "rgba(208, 226, 182, 0.34)",
    backgroundColor: "rgba(176, 199, 142, 0.18)",
  },
  detailHeroSubmitCardPendingSync: {
    borderColor: "rgba(231, 194, 129, 0.34)",
    backgroundColor: "rgba(204, 112, 31, 0.12)",
  },
  detailHeroSubmitCardBlocked: {
    borderColor: "rgba(228, 165, 149, 0.34)",
    backgroundColor: "rgba(205, 88, 51, 0.12)",
  },
  detailHeroSubmitHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  detailHeroSubmitHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  detailHeroSubmitTitle: {
    ...brandTypography.label,
    color: brandColors.white,
  },
  detailHeroSubmitBody: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  detailHeroSubmitPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  detailHeroSubmitPillText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  detailHeroSubmitButtonInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.white,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  detailHeroSubmitButtonCompact: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  detailHeroSubmitButtonText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  detailHeroShell: {
    position: "relative",
    minHeight: 320,
    borderRadius: 30,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: "#132434",
    ...brandShadow.card,
  },
  detailHeroMain: {
    width: "100%",
    height: 320,
    backgroundColor: "#132434",
  },
  detailHeroMap: {
    width: "100%",
    height: "100%",
    backgroundColor: "#132434",
  },
  detailHeroPhotoCarousel: {
    width: "100%",
    height: "100%",
  },
  detailHeroPhotoSlide: {
    height: "100%",
  },
  detailHeroPhotoImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#132434",
  },
  detailHeroOverlayBadge: {
    position: "absolute",
    left: 14,
    bottom: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(8, 13, 19, 0.72)",
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  detailHeroOverlayBadgeText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  detailHeroSwitchThumb: {
    position: "absolute",
    left: 14,
    top: 14,
    width: 78,
    height: 78,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "#132434",
  },
  detailHeroSwitchThumbImage: {
    width: "100%",
    height: "100%",
  },
  detailHeroSwitchThumbMap: {
    width: "100%",
    height: "100%",
  },
  detailHeroSwitchThumbLabel: {
    position: "absolute",
    left: 6,
    right: 6,
    bottom: 6,
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(8, 13, 19, 0.72)",
    paddingVertical: 4,
  },
  detailHeroSwitchThumbLabelText: {
    ...brandTypography.meta,
    color: brandColors.white,
    textAlign: "center",
  },
  detailHeroActions: {
    position: "absolute",
    top: 14,
    right: 14,
    gap: 8,
  },
  detailHeroActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
    backgroundColor: "rgba(8, 13, 19, 0.72)",
  },
  detailHeroActionButtonDanger: {
    backgroundColor: "rgba(129, 31, 31, 0.84)",
    borderColor: "rgba(255, 210, 210, 0.42)",
  },
  filterChipsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  filterChip: {
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterChipActive: {
    borderColor: brandColors.forest,
    backgroundColor: brandColors.forest,
  },
  filterChipStatic: {
    opacity: 1,
  },
  filterChipSuccess: {
    backgroundColor: brandColors.successSoft,
    borderColor: "#BBD09B",
  },
  filterChipWarning: {
    backgroundColor: "#F7E6CA",
    borderColor: "#E7C281",
  },
  filterChipDanger: {
    backgroundColor: brandColors.errorSoft,
    borderColor: "#E4A595",
  },
  filterChipText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  filterChipTextActive: {
    color: brandColors.white,
  },
  detailSection: {
    gap: 12,
  },
  detailMetadataCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 12,
    ...brandShadow.card,
  },
  detailTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 22,
    lineHeight: 25,
    color: brandColors.forest,
  },
  panelBody: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  detailParcelsEditButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panelMuted,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  detailParcelsEditButtonText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  summaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  summaryItem: {
    color: brandColors.forest,
    backgroundColor: brandColors.panelMuted,
  },
  summaryItemLabel: {
    color: brandColors.forest,
  },
  scoreHeroCard: {
    borderRadius: 24,
    backgroundColor: brandColors.successSoft,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 4,
  },
  scoreHeroLabel: {
    ...brandTypography.heroEyebrow,
    color: brandColors.textSecondary,
  },
  scoreHeroValue: {
    fontSize: 32,
    lineHeight: 36,
    fontWeight: "900",
    color: brandColors.forest,
  },
  scoreHeroMeta: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  factorTilesCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 12,
    ...brandShadow.card,
  },
  factorTotalsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  factorTotalPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.panelMuted,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  factorTotalText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  factorTilesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  factorTile: {
    width: "31%",
    minWidth: 98,
    flexGrow: 1,
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 6,
  },
  factorTileCompleted: {
    borderColor: "#B8CFA4",
    backgroundColor: brandColors.successSoft,
  },
  factorTilePending: {
    borderColor: brandColors.divider,
    backgroundColor: brandColors.white,
  },
  factorTileEditable: {
    borderColor: brandColors.divider,
  },
  factorTileTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  factorTileIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  factorBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandColors.forest,
  },
  factorBadgeText: {
    ...brandTypography.label,
    fontSize: 12,
    lineHeight: 14,
    color: brandColors.white,
  },
  factorTileIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandColors.panelMuted,
  },
  factorTileIconWrapCompleted: {
    backgroundColor: brandColors.panelMuted,
  },
  factorTileIconWrapPending: {
    backgroundColor: brandColors.panelMuted,
  },
  factorTileClass: {
    ...brandTypography.label,
    fontSize: 13,
    lineHeight: 16,
    color: brandColors.textPrimary,
  },
  factorTileCode: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  factorTileClassCompleted: {
    color: brandColors.forest,
  },
  factorTileClassPending: {
    color: brandColors.textSecondary,
  },
  factorTileStatusPill: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  factorTileStatusPillCompleted: {
    backgroundColor: "#DCE7C4",
  },
  factorTileStatusPillPending: {
    backgroundColor: brandColors.panelMuted,
  },
  factorTileWarning: {
    ...brandTypography.meta,
    color: brandColors.terracotta,
  },
  actionPanel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 12,
    ...brandShadow.card,
  },
  actionButtonsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: brandRadius.pill,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
  },
  actionButtonNeutral: {
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panelMuted,
  },
  actionButtonPrimary: {
    borderColor: brandColors.forest,
    backgroundColor: brandColors.forest,
  },
  actionButtonDanger: {
    borderColor: "#E2A495",
    backgroundColor: brandColors.errorSoft,
  },
  actionButtonSuccess: {
    borderColor: "#BBD09B",
    backgroundColor: brandColors.successSoft,
  },
  actionButtonText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  actionButtonTextPrimary: {
    color: brandColors.white,
  },
  actionButtonTextDanger: {
    color: brandColors.terracotta,
  },
  submittedReadonlyBanner: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#BBD09B",
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 8,
  },
  submittedReadonlyBannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  submittedReadonlyBannerTitle: {
    ...brandTypography.label,
    color: brandColors.forest,
  },
  submittedReadonlyBannerText: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  deadlineCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 6,
  },
  deadlineCardWarning: {
    borderColor: "#E7C281",
    backgroundColor: "#FDF2DF",
  },
  deadlineLabel: {
    ...brandTypography.heroEyebrow,
    color: brandColors.textSecondary,
  },
  deadlineValue: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: "900",
    color: brandColors.forest,
  },
  deadlineValueWarning: {
    color: brandColors.ochre,
  },
  rowMeta: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  warningText: {
    ...brandTypography.meta,
    color: brandColors.ochre,
  },
  eventsCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 12,
    ...brandShadow.card,
  },
  eventRow: {
    gap: 4,
    borderTopWidth: 1,
    borderTopColor: brandColors.divider,
    paddingTop: 12,
  },
  eventTitle: {
    ...brandTypography.label,
    color: brandColors.forest,
  },
  eventPayload: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  debugCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 18,
    gap: 6,
    ...brandShadow.card,
  },
  debugAttachmentBlock: {
    gap: 10,
  },
  debugSectionTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 22,
    lineHeight: 25,
    color: brandColors.forest,
  },
  debugAttachmentCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 14,
    gap: 6,
  },
  debugAttachmentPreview: {
    width: "100%",
    height: 180,
    borderRadius: 18,
    backgroundColor: brandColors.panelMuted,
  },
  debugAttachmentPreviewPlaceholder: {
    width: "100%",
    height: 180,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandColors.panelMuted,
  },
})
