import { Platform, StyleSheet } from "react-native"
import { brandColors, brandRadius, brandShadow, brandTypography } from "../app/brand-tokens"

export const screenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: brandColors.canvas,
  },
  heroShell: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 2,
    paddingTop: 10,
    paddingHorizontal: 16,
  },
  heroCard: {
    flex: 1,
    position: "relative",
    overflow: "hidden",
    borderRadius: 34,
    backgroundColor: brandColors.forest,
    ...brandShadow.card,
  },
  heroAccentOrb: {
    position: "absolute",
    top: -24,
    right: -18,
    width: 126,
    height: 126,
    borderRadius: 999,
    backgroundColor: "rgba(176, 199, 142, 0.22)",
  },
  heroExpandedLayer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
    paddingTop: 18,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  heroExpandedHeader: {
    gap: 8,
    paddingRight: 46,
  },
  heroEyebrow: {
    ...brandTypography.heroEyebrow,
    color: "#D7E3C0",
  },
  heroTitleExpanded: {
    ...brandTypography.heroTitle,
    fontSize: 30,
    lineHeight: 34,
    color: brandColors.white,
  },
  heroBody: {
    ...brandTypography.heroBody,
    fontSize: 13,
    lineHeight: 18,
    color: "#E4ECD8",
    maxWidth: 300,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroMetaPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  heroMetaPillText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  heroCompactLayer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
    paddingHorizontal: 20,
    paddingRight: 64,
    paddingBottom: 12,
    gap: 8,
  },
  heroCompactSummary: {
    ...brandTypography.meta,
    color: "#D7E3C0",
  },
  compactProgressWrap: {
    gap: 5,
  },
  compactProgressCount: {
    ...brandTypography.heroEyebrow,
    fontSize: 10,
    lineHeight: 12,
    color: "#D7E3C0",
  },
  compactProgressTrack: {
    flexDirection: "row",
    gap: 6,
  },
  compactProgressSegment: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
  },
  compactProgressSegmentActive: {
    backgroundColor: brandColors.white,
  },
  compactProgressSegmentComplete: {
    backgroundColor: "#D7E3C0",
  },
  pageScroll: {
    flex: 1,
  },
  pageContent: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 108,
    gap: 10,
  },
  stepRailWrap: {
    zIndex: 1,
    overflow: "hidden",
    paddingBottom: 0,
  },
  stepRailCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 6,
    ...brandShadow.card,
  },
  stepRow: {
    flexDirection: "row",
    gap: 8,
  },
  stepButton: {
    flex: 1,
    minHeight: 72,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.white,
    paddingHorizontal: 9,
    paddingVertical: 7,
    gap: 2,
  },
  stepButtonActive: {
    borderColor: brandColors.forest,
    backgroundColor: brandColors.forest,
  },
  stepButtonComplete: {
    borderColor: brandColors.moss,
    backgroundColor: brandColors.successSoft,
  },
  stepButtonDisabled: {
    opacity: 0.52,
  },
  stepButtonTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  stepIndexPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.panelMuted,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  stepIndexPillActive: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
  },
  stepIndexText: {
    ...brandTypography.heroEyebrow,
    fontSize: 10,
    lineHeight: 12,
    color: brandColors.forest,
  },
  stepIndexTextActive: {
    color: brandColors.white,
  },
  stepButtonTitle: {
    ...brandTypography.label,
    color: brandColors.textPrimary,
  },
  stepButtonTitleActive: {
    color: brandColors.white,
  },
  stepButtonMeta: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  stepButtonMetaActive: {
    color: "#D7E3C0",
  },
  stepButtonHint: {
    marginTop: "auto",
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  stepButtonHintActive: {
    color: brandColors.white,
  },
  panel: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panel,
    padding: 16,
    gap: 10,
    ...brandShadow.card,
  },
  identityStepContent: {
    gap: 10,
  },
  panelHeader: {
    gap: 3,
  },
  panelHeaderCompact: {
    flex: 1,
    gap: 3,
  },
  panelTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 19,
    lineHeight: 22,
    color: brandColors.forest,
  },
  panelBody: {
    ...brandTypography.sectionBody,
    fontSize: 12,
    lineHeight: 17,
    color: brandColors.textSecondary,
  },
  label: {
    ...brandTypography.label,
    color: brandColors.textPrimary,
  },
  input: {
    borderWidth: 1,
    borderColor: brandColors.inputBorder,
    borderRadius: brandRadius.field,
    backgroundColor: brandColors.inputFill,
    color: brandColors.textPrimary,
    paddingHorizontal: 14,
    paddingVertical: 12,
    ...brandTypography.input,
  },
  errorText: {
    ...brandTypography.meta,
    color: brandColors.terracotta,
  },
  choiceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  choiceChip: {
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.inputBorder,
    backgroundColor: brandColors.panelMuted,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  choiceChipActive: {
    borderColor: brandColors.forest,
    backgroundColor: brandColors.forest,
  },
  choiceChipText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  choiceChipTextActive: {
    color: brandColors.white,
  },
  parcelHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  selectionCountPill: {
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.forest,
    backgroundColor: brandColors.successSoft,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  selectionCountPillText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  secondaryPillButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.panelMuted,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  secondaryPillButtonText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  mapFrame: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.canvas,
  },
  mapOverlayActions: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-start",
    alignItems: "flex-end",
    padding: 12,
  },
  mapOverlayButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(22, 47, 31, 0.76)",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapOverlayButtonText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  map: {
    width: "100%",
    height: 408,
  },
  mapHelperText: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  selectionSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  selectionPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.successSoft,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  selectionPillText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  infoCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.white,
    padding: 14,
    gap: 6,
  },
  infoCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  infoCardTitle: {
    ...brandTypography.label,
    color: brandColors.forest,
  },
  infoCardBody: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  fullscreenMapScreen: {
    flex: 1,
    backgroundColor: "#132434",
  },
  fullscreenMap: {
    flex: 1,
  },
  fullscreenMapOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
  },
  fullscreenMapTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: "rgba(247, 246, 240, 0.96)",
    paddingHorizontal: 12,
    paddingVertical: Platform.select({ ios: 6, default: 10 }),
  },
  fullscreenMapTopTitle: {
    flex: 1,
    textAlign: "center",
    ...brandTypography.label,
    color: brandColors.forest,
  },
  fullscreenMapCloseButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
    backgroundColor: "rgba(8, 13, 19, 0.72)",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  fullscreenMapCloseText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  fullscreenMapFloatingActions: {
    alignSelf: "flex-end",
  },
  fullscreenMapActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "#8EA97C",
    backgroundColor: brandColors.forest,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: brandRadius.pill,
    ...brandShadow.card,
  },
  fullscreenMapActionButtonText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  fullscreenMapBottomArea: {
    gap: 12,
  },
  fullscreenMapBottomSheet: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: "rgba(247, 246, 240, 0.97)",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
    ...brandShadow.card,
  },
  fullscreenMapBottomTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 20,
    lineHeight: 24,
    color: brandColors.forest,
  },
  fullscreenMapBottomMeta: {
    ...brandTypography.sectionBody,
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.textSecondary,
  },
  fullscreenMapBottomHint: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  fullscreenMapWarningCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E7B8AA",
    backgroundColor: "#F6E1DA",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fullscreenMapWarningText: {
    flex: 1,
    ...brandTypography.meta,
    color: brandColors.terracotta,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
  },
  secondaryButton: {
    minWidth: 104,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.inputBorder,
    backgroundColor: brandColors.panel,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    ...brandTypography.button,
    color: brandColors.forest,
  },
  primaryButton: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.forest,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 13,
    ...brandShadow.card,
  },
  primaryButtonDisabled: {
    opacity: 0.48,
  },
  primaryButtonWide: {
    flex: 1,
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.forest,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 15,
    ...brandShadow.card,
  },
  primaryButtonText: {
    ...brandTypography.button,
    color: brandColors.white,
  },
  scoreHeroCard: {
    borderRadius: 28,
    backgroundColor: brandColors.white,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 4,
    ...brandShadow.card,
  },
  scoreHeroLabel: {
    ...brandTypography.heroEyebrow,
    color: brandColors.textSecondary,
  },
  scoreHeroValue: {
    fontSize: 52,
    lineHeight: 56,
    fontWeight: "900",
    color: brandColors.forest,
  },
  scoreHeroMeta: {
    ...brandTypography.sectionBody,
    color: brandColors.textSecondary,
  },
  factorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  factorTile: {
    width: "30.5%",
    minWidth: 92,
    flexGrow: 1,
    borderRadius: 18,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 4,
    borderWidth: 1,
  },
  factorTilePending: {
    borderColor: brandColors.divider,
    backgroundColor: brandColors.white,
  },
  factorTileComplete: {
    borderColor: brandColors.moss,
    backgroundColor: brandColors.successSoft,
  },
  factorTileWarning: {
    borderColor: brandColors.terracotta,
    backgroundColor: "#F9E5DF",
  },
  factorTileTopRow: {
    flexDirection: "row",
    gap: 6,
    justifyContent: "space-between",
    alignItems: "center",
  },
  factorTileIdentity: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  factorBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandColors.forest,
  },
  factorBadgeText: {
    ...brandTypography.label,
    fontSize: 11,
    lineHeight: 12,
    color: brandColors.white,
  },
  factorIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: brandColors.panelMuted,
  },
  factorTileTitle: {
    ...brandTypography.label,
    fontSize: 11,
    lineHeight: 13,
    color: brandColors.textPrimary,
  },
  factorTileMeta: {
    ...brandTypography.meta,
    fontSize: 10,
    lineHeight: 12,
    color: brandColors.textSecondary,
  },
  factorTileState: {
    ...brandTypography.meta,
    fontSize: 10,
    lineHeight: 12,
    color: brandColors.forest,
  },
})
